### ISSUE TITLE
Issueの使い方

### ISSUE THREAD

**Issue by tanacchi** [tanacchi/GitLesson#1]
githubには Issue(イシュー↴) という機能があります。
Issue は主に話し合いの場として利用されます。
感覚としてはネットの掲示板・スレッドに近いものがあります。
本講義では開発方針の検討のほか、質問受け付けの場としても利用したいと思っています。

## Issueの立て方
![gitlesson home](https://user-images.githubusercontent.com/19949534/39471557-b8407608-4d7e-11e8-9155-516ce016febc.png)
##### Issue は上の赤い丸で囲まれたところから参照できます。

![gitlesson issue](https://user-images.githubusercontent.com/19949534/39471590-e10d1442-4d7e-11e8-81ed-ecc722f0332a.png)
##### 新規作成する場合は緑色の「New issue」をクリックしてください。

![gitlesson issue new](https://user-images.githubusercontent.com/19949534/39471649-29ce464c-4d7f-11e8-90cc-d8d0a38e3569.png)
##### 説明の部分は省略可能です。
![gitlesson issue list](https://user-images.githubusercontent.com/19949534/39471681-7057884e-4d7f-11e8-98af-4d7a26680bbe.png)
##### 完成したらこのようになります。

ご利用お待ちしております。

**Comment by rkdora** [comment]
Thank you!

**Comment by tanacchi** [comment]
Hi

**Comment by tanacchi** [comment]
test

**Comment by tanacchi** [comment]
こういう記事はwiki かMarkDown にして管理する方がいいですね
